version: '3'

services:
    api:
        build:
            context: .
            dockerfile: ./compose/Django/Dockerfile
        environment:
            - DJANGO_DEBUG=True
        ports:
            - "80:8080"
        command: /bin/bash
        # python manage.py runserver 0:8080
        volumes:
            - ./project/:/app/